import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { load, newProject } from "../src/funcs";
import Modal from "react-modal/lib/components/Modal";
import { NavBar } from "../components/navBar";
import { ProjectsContainer } from "../components/projectsContainer";
import Web3 from "web3";

export default function Home() {
  // useState
  const [refresh, setRefresh] = useState(true);
  const [modalIsOpen, setIsOpen] = useState(false);
  const [addressAccount, setAddressAccount] = useState(null);
  const [crowdfundingContract, setCrowdfundingContract] = useState(null);
  const [projectContracts, setProjectContracts] = useState(null);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [goal, setGoal] = useState(0);

  // useEffect
  useEffect(() => {
    if (!refresh) return;
    setRefresh(false);
    load().then((e) => {
      setAddressAccount(e.addressAccount);
      setCrowdfundingContract(e.crowdfundingContract);
      setProjectContracts(e.projectContracts);
    });

    window.ethereum.on("accountsChanged", async () => {
      load().then((e) => {
        setAddressAccount(e.addressAccount);
        setCrowdfundingContract(e.crowdfundingContract);
        setProjectContracts(e.projectContracts);
      });
    });
  }, []);

  function openModal() {
    setIsOpen(true);
  }

  function closeModal() {
    setIsOpen(false);
  }

  const handleNewProject = async () => {
    crowdfundingContract.createProject(title, description, goal, {
      from: addressAccount,
    });
    setRefresh(true);
  };

  return (
    <>
      <NavBar addressAccount={addressAccount} />
      <div className={styles.container}>
        <Head>
          <title>Blockchain Crowdfunding</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <button onClick={openModal}>New project</button>
        <ProjectsContainer projectContracts={projectContracts} />
        <Modal
          isOpen={modalIsOpen}
          onRequestClose={closeModal}
          contentLabel="Example Modal"
        >
          <button className="text-red-500 font-black" onClick={closeModal}>X</button>
        <form>
          <input
            className="border-2"
            type="text"
            id="title"
            onChange={(e) => setTitle(e.target.value)}
          ></input>
          <input
            className="border-2"
            type="text"
            id="description"
            onChange={(e) => setDescription(e.target.value)}
          ></input>
          <input
            className="border-2"
            type="number"
            id="goal"
            onChange={(e) => setGoal(e.target.value)}
          ></input>
        </form>
        <button onClick={handleNewProject}>New project</button>
        </Modal>
      </div>
    </>
  );
}
